create table if not exists public.listings (
  id bigint generated by default as identity primary key,
  title text not null,
  area text not null,
  city text not null default 'Addis Ababa',
  price integer not null check (price >= 0),
  beds integer not null default 1 check (beds >= 0),
  baths integer not null default 1 check (baths >= 0),
  type text not null default 'Apartment',
  broker text not null,
  description text not null,
  image_url text not null,
  verified boolean not null default false,
  created_at timestamptz not null default now()
);

alter table public.listings enable row level security;

create policy "Anyone can read listings"
  on public.listings for select
  to anon, authenticated
  using (true);

create policy "Anyone can create listings"
  on public.listings for insert
  to anon, authenticated
  with check (true);

insert into storage.buckets (id, name, public)
values ('listing-images', 'listing-images', true)
on conflict (id) do nothing;

create policy "Anyone can view listing images"
  on storage.objects for select
  to anon, authenticated
  using (bucket_id = 'listing-images');

create policy "Anyone can upload listing images"
  on storage.objects for insert
  to anon, authenticated
  with check (bucket_id = 'listing-images');
